#! /bin/bash

if [ "`uname`" == "Linux" ]; then
  [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
  apt-get update

  apt-get -q -y install software-properties-common curl \
    apt-transport-https ca-certificates

  add-apt-repository -y ppa:nginx/stable
  add-apt-repository -y ppa:git-core/ppa
  add-apt-repository -y ppa:webupd8team/java
  add-apt-repository -y ppa:pi-rho/dev
  # add-apt-repository -y ppa:keithw/mosh # atm regular ubuntu repo is more up to date with sigsev fix


  # Docker
  apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
cat > /etc/apt/sources.list.d/docker.list <<!
deb https://apt.dockerproject.org/repo ubuntu-xenial main
!

  apt-get update
  apt-get -q -y install linux-image-extra-$(uname -r)
  apt-get -q -y install docker-engine
  service docker start

  groupadd docker
  usermod -aG docker laurent

  docker run hello-world

  apt-get update
  apt-get upgrade

  echo "checkout install docker compose at: https://github.com/docker/compose/releases"

elif [ "`uname`" == "Darwin" ]; then
    sudo spctl --master-disable # gatekeeper allow apps from everywhere
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    open 'https://www.docker.com/'
    open 'https://www.vagrantup.com/'
    open 'https://www.jetbrains.com/idea/'

fi
