#! /bin/bash

if [ "`uname`" == "Linux" ]; then
  [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
  apt-get update

  apt-get -q -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

  add-apt-repository -y ppa:webupd8team/java
  add-apt-repository -y ppa:git-core/ppa
  add-apt-repository -y ppa:neovim-ppa/unstable
  # add-apt-repository -y ppa:pi-rho/dev # tmux?
  # add-apt-repository -y ppa:nathan-renniewaldock/flux # server only
  # add-apt-repository -y ppa:keithw/mosh # atm regular ubuntu repo is more up to date with sigsev fix

  # Docker
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  apt-key fingerprint 0EBFCD88
  add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

  apt-get update
  apt-get upgrade
  apt-get -q -y install linux-image-extra-$(uname -r)
  apt-get -q -y install docker-ce
  service docker start

  groupadd docker
  usermod -aG docker laurent

  docker run hello-world

  apt-get update
  apt-get upgrade

  echo "checkout install docker compose at: https://github.com/docker/compose/releases"
elif [ "`uname`" == "Darwin" ]; then
    sudo spctl --master-disable # gatekeeper allow apps from everywhere
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    open 'https://www.docker.com/'
    open 'https://www.vagrantup.com/'
    open 'https://www.jetbrains.com/idea/'
fi
