#! /bin/sh
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

if [ "`uname`" = "Linux" ]; then
  apt-get -q -y install vim zsh  \
        python python-dev \
	python3 python3-dev \
	python3-pip \
  	libfreetype6-dev libncurses5-dev libxft-dev git \
  	ack-grep autojump tree colordiff grc htop tmux \
	unison mosh \
	libpq-dev

  pip3 install --upgrade pip

  echo "Setting default java: 1.8"
  echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  apt-get -q -y install oracle-java8-installer
  update-java-alternatives -s java-8-oracle

  # Leiningen Clojure
  if [ ! `which lein` ]; then
    cd /usr/bin && wget https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod a+x lein;
    lein > /dev/null
  fi

  # Services
  apt-get -q -y install sysvinit-utils ufw

  pip3 install tmuxp ipython jupyter matplotlib virtualenv \
    virtualenvwrapper

  ufw allow ssh
  ufw allow http
  ufw allow https
  ufw allow 60000:61000/udp # mosh ports
  ufw enable


elif [ "`uname`" = 'Darwin' ]; then
  brew install python python3
  echo "checkout the logs to linkapps stuff"
  read
  brew install reattach-to-user-namespace unison tree macvim vim postgresql
  echo "checkout the logs to linkapps stuff"
  read

  pip3 install tmuxp ipython jupyter matplotlib

fi
