#! /bin/sh
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

HOME=~
INSTALL=`pwd`
mail="laurent.senta@gmail.com"

oldIfExist()
{
    if [ -e "$1" ]; then
        oldIfExist "$1-old"

        mv "$1" "$1-old"
    fi
}

autoLink()
{
    real="$INSTALL/$1"
    dest="$HOME/$2"

    oldIfExist "$dest"
    ln "$real" "$dest" $3
}

autoLinkS()
{
    autoLink $1 $2 -s
}

# == Colors
./system/gnome-terminal-colors-solarized/solarize


# == UI tools
apt-add-repository -y ppa:tycho-s/ppa

apt-get update

apt-get -q -y install vim-gtk
apt-get -q -y install awesome awesome-extra suckless-tools
apt-get -q -y install dropbox nautilus-dropbox fluxgui freemind

# == Node & Typescript
apt-get -q -y install nodejs npm

npm install -g http-server
npm install -g typescript

# typescript compiler looks for node executable:
cd /usr/bin && ln -s /usr/bin/nodejs node && cd -


# == Docker configuration
echo "Add ${USER} to docker group, logout required for change to be effective"
gpasswd -a ${USER} docker
service docker restart

autoLinkS awesome .config/awesome

echo "edit /etc/sysctl.conf"
echo "add: 'fs.inotify.max_user_watches = 524288'"
echo "run: 'sudo sysctl -p'"
