#! /bin/sh
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

HOME=~
INSTALL=`pwd`
mail="laurent.senta@gmail.com"

oldIfExist()
{
    if [ -e "$1" ]; then
        oldIfExist "$1-old"

        mv "$1" "$1-old"
    fi
}

autoLink()
{
    real="$INSTALL/$1"
    dest="$HOME/$2"

    oldIfExist "$dest"
    ln "$real" "$dest" $3
}

autoLinkS()
{
    autoLink $1 $2 -s
}

# Colors
./system/gnome-terminal-colors-solarized/solarize

apt-add-repository -y ppa:tycho-s/ppa

apt-get update

apt-get -q -y install vim-gtk
apt-get -q -y install awesome awesome-extra suckless-tools
apt-get -q -y install dropbox nautilus-dropbox fluxgui freemind
apt-get -q -y install qtile


autoLinkS awesome .config/awesome
